'use client';

import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { Provider } from "react-redux";
import { store } from "../../store/store.js";
import { ToastContainer } from "react-toastify";

import Navigation from "@/components/Navigation";
import Footer from "@/components/Footer";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const metadata = {
  title: "medium",
  description: "Generated by create next app",
};



const queryClient = new QueryClient();
export default function RootLayout({ children }) {
  return (
     <html lang="en">
      <body className="antialiased w-full flex flex-col">
        <Provider store={store}>
           <QueryClientProvider client={queryClient} >
                  <ToastContainer autoClose={500} />
          <Navigation />
          {children}
           <Footer />
           </QueryClientProvider>
        </Provider>
      </body>
    </html>
  );
}
