'use client';

import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { Provider } from "react-redux";
import { store } from "../../store/store.js";
import { ToastContainer } from "react-toastify";

import Navigation from "@/components/Navigation";
import Footer from "@/components/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const metadata = {
  title: "medium",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
     <html lang="en">
      <body className="antialiased w-full flex flex-col">
        <Provider store={store}>
          <Navigation />
          {children}
          <ToastContainer />
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
